services:
  # --- LA GATEWAY ---
  gateway:
    build:
      context: ./gateway
    ports:
      - "80:80"
    depends_on:
      - front
      - service-auth
      - service-post
      - service-user

  # --- LES BASES DE DONNÉES ---
  db-auth:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: auth_db
    volumes:
      - pg_auth_data:/var/lib/postgresql/data

  db-user:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    volumes:
      - pg_user_data:/var/lib/postgresql/data

  db-post:
    image: mongo:latest
    volumes:
      - mongo_post_data:/data/db

  # --- LE FRONT ---
  front:
    build:
      context: ./front

  # --- LES MICROSERVICES ---
  service-auth:
    build:
      context: ./Services/Auth
    environment:
      - NODE_ENV=dev
      - API_PORT=3000
      - DB_HOST=db-auth
      - DB_PORT=5432
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=auth_db
      - JWT_SECRET=oeL0xvKleZvALGWVwMWadS00Us47Rh3GH8EC6dfbW5w=
      - JWT_EXPIRES_IN=1h
      - SALT_ROUNDS=12
    depends_on:
      - db-auth

  service-user:
    build:
      context: ./Services/User
    environment:
      - DB_HOST=db-user
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_NAME=user_db
    depends_on:
      - db-user

  service-post:
    build:
      context: ./Services/Post
    environment:
      - API_PORT=3000
      - MONGO_URI=mongodb://db-post:27017/post_db
      - JWT_SECRET=oeL0xvKleZvALGWVwMWadS00Us47Rh3GH8EC6dfbW5w=
    depends_on:
      - db-post

volumes:
  pg_auth_data:
  pg_user_data:
  mongo_post_data: