events { worker_connections 1024; }

http {
    server {
        listen 80;

        location /api/v1/auth/ {
            proxy_pass http://service-auth:3000/api/v1/auth/;
            proxy_set_header Host $host;
        }

        location /api/v1/post/ {
            proxy_pass http://service-post:3000/api/;
            proxy_set_header Host $host;
        }

        location /api/v1/user/ {
            proxy_pass http://service-user:3000/api/;
            proxy_set_header Host $host;
        }

        location / {
            proxy_pass http://front:3000;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}