events { worker_connections 1024; }

http {
    server {
        listen 80;

        # Redirection vers le service d'authentification
        location /api/v1/auth/ {
            proxy_pass http://service-auth:3000/;
            proxy_set_header Host $host;
        }

        # Redirection vers le service des posts
        location /api/v1/post/ {
            proxy_pass http://service-post:3000/;
            proxy_set_header Host $host;
        }

        # Redirection vers le service des utilisateurs
        location /api/v1/user/ {
            proxy_pass http://service-user:3000/;
            proxy_set_header Host $host;
        }

        # Redirection par défaut vers le Front-end
        location / {
            proxy_pass http://front:3000;
            proxy_set_header Host $host;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
        }
    }
}